-- Supabase SQL bootstrap for ICTHubs
-- Enhanced schema with admin system, analytics, notifications, and media management
-- Run in SQL editor if you prefer raw SQL over Prisma.

create extension if not exists "pgcrypto";

-- ============================================
-- USERS & ROLES MANAGEMENT
-- ============================================

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  permissions jsonb default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  full_name text,
  role_id bigint references public.roles(id) on delete set null,
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_users_role_id on public.users(role_id);
create index if not exists idx_users_deleted_at on public.users(deleted_at) where deleted_at is null;

-- ============================================
-- BOOKINGS (Enhanced)
-- ============================================

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  service text not null,
  message text not null,
  status text not null default 'pending',
  assigned_to uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_bookings_status on public.bookings(status);
create index if not exists idx_bookings_assigned_to on public.bookings(assigned_to);
create index if not exists idx_bookings_created_at on public.bookings(created_at desc);
create index if not exists idx_bookings_deleted_at on public.bookings(deleted_at) where deleted_at is null;

alter table public.bookings enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'bookings'
      and p.policyname = 'Allow public inserts'
  ) then
    create policy "Allow public inserts" on public.bookings
    for insert to anon
    with check (true);
  end if;
end
$$;

-- ============================================
-- BLOG POSTS (Enhanced)
-- ============================================

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  excerpt text,
  content text,
  author_id uuid references public.users(id) on delete set null,
  published boolean not null default false,
  published_at timestamptz,
  views_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_posts_slug on public.posts(slug);
create index if not exists idx_posts_published on public.posts(published, published_at desc);
create index if not exists idx_posts_author_id on public.posts(author_id);
create index if not exists idx_posts_deleted_at on public.posts(deleted_at) where deleted_at is null;

alter table public.posts enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'posts'
      and p.policyname = 'Allow anon read published'
  ) then
    create policy "Allow anon read published" on public.posts
    for select to anon
    using (published = true and deleted_at is null);
  end if;
end
$$;

-- ============================================
-- CATEGORIES & TAGS
-- ============================================

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_categories_slug on public.categories(slug);
create index if not exists idx_categories_deleted_at on public.categories(deleted_at) where deleted_at is null;

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_tags_slug on public.tags(slug);
create index if not exists idx_tags_deleted_at on public.tags(deleted_at) where deleted_at is null;

create table if not exists public.posts_categories (
  post_id bigint references public.posts(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  primary key (post_id, category_id)
);

create index if not exists idx_posts_categories_post_id on public.posts_categories(post_id);
create index if not exists idx_posts_categories_category_id on public.posts_categories(category_id);

create table if not exists public.posts_tags (
  post_id bigint references public.posts(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

create index if not exists idx_posts_tags_post_id on public.posts_tags(post_id);
create index if not exists idx_posts_tags_tag_id on public.posts_tags(tag_id);

alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.posts_categories enable row level security;
alter table public.posts_tags enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'categories'
      and p.policyname = 'Allow anon select categories'
  ) then
    create policy "Allow anon select categories" on public.categories
    for select to anon
    using (deleted_at is null);
  end if;
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'tags'
      and p.policyname = 'Allow anon select tags'
  ) then
    create policy "Allow anon select tags" on public.tags
    for select to anon
    using (deleted_at is null);
  end if;
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'posts_categories'
      and p.policyname = 'Allow anon select posts_categories'
  ) then
    create policy "Allow anon select posts_categories" on public.posts_categories
    for select to anon
    using (true);
  end if;
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'posts_tags'
      and p.policyname = 'Allow anon select posts_tags'
  ) then
    create policy "Allow anon select posts_tags" on public.posts_tags
    for select to anon
    using (true);
  end if;
end
$$;

-- ============================================
-- CONTACT MESSAGES (public form submissions)
-- ============================================

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_contact_messages_email on public.contact_messages(email);
create index if not exists idx_contact_messages_created_at on public.contact_messages(created_at desc);

alter table public.contact_messages enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies p
    where p.schemaname = 'public'
      and p.tablename = 'contact_messages'
      and p.policyname = 'Allow public contact inserts'
  ) then
    create policy "Allow public contact inserts" on public.contact_messages
    for insert to anon
    with check (true);
  end if;
end
$$;

-- ============================================
-- ADMIN ACTIVITY LOGS
-- ============================================

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_logs_user_id on public.activity_logs(user_id);
create index if not exists idx_activity_logs_action on public.activity_logs(action);
create index if not exists idx_activity_logs_entity on public.activity_logs(entity_type, entity_id);
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);

-- ============================================
-- NOTIFICATIONS SYSTEM
-- ============================================

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text,
  link text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_id on public.notifications(user_id, is_read);
create index if not exists idx_notifications_created_at on public.notifications(created_at desc);

-- ============================================
-- ANALYTICS & METRICS
-- ============================================

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_name text not null,
  page_url text,
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_event_type on public.analytics_events(event_type);
create index if not exists idx_analytics_event_name on public.analytics_events(event_name);
create index if not exists idx_analytics_created_at on public.analytics_events(created_at desc);
create index if not exists idx_analytics_user_id on public.analytics_events(user_id);

create table if not exists public.analytics_summaries (
  id bigint generated by default as identity primary key,
  date date not null unique,
  total_visits bigint not null default 0,
  unique_visitors bigint not null default 0,
  total_bookings bigint not null default 0,
  total_page_views bigint not null default 0,
  bounce_rate numeric(5,2),
  avg_session_duration interval,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_analytics_summaries_date on public.analytics_summaries(date desc);

-- ============================================
-- MEDIA & FILE MANAGEMENT
-- ============================================

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  filename text not null,
  original_filename text not null,
  file_path text not null,
  file_size bigint,
  mime_type text,
  width integer,
  height integer,
  uploaded_by uuid references public.users(id) on delete set null,
  alt_text text,
  caption text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_media_uploaded_by on public.media(uploaded_by);
create index if not exists idx_media_mime_type on public.media(mime_type);
create index if not exists idx_media_created_at on public.media(created_at desc);
create index if not exists idx_media_deleted_at on public.media(deleted_at) where deleted_at is null;

-- ============================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger roles_set_updated_at before update on public.roles
for each row execute function public.set_updated_at();

create trigger users_set_updated_at before update on public.users
for each row execute function public.set_updated_at();

create trigger bookings_set_updated_at before update on public.bookings
for each row execute function public.set_updated_at();

create trigger posts_set_updated_at before update on public.posts
for each row execute function public.set_updated_at();

create trigger analytics_summaries_set_updated_at before update on public.analytics_summaries
for each row execute function public.set_updated_at();

create trigger media_set_updated_at before update on public.media
for each row execute function public.set_updated_at();

-- keep categories/tags updated_at fresh
create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();

create trigger tags_set_updated_at before update on public.tags
for each row execute function public.set_updated_at();

-- ============================================
-- SEED DATA
-- ============================================

-- Default roles
insert into public.roles (name, description, permissions)
values
  ('super_admin', 'Full system access', '["all"]'::jsonb),
  ('admin', 'Administrative access', '["manage_users", "manage_content", "view_analytics"]'::jsonb),
  ('editor', 'Content management', '["manage_content"]'::jsonb),
  ('viewer', 'Read-only access', '["view_content"]'::jsonb)
on conflict (name) do nothing;

-- Seed a couple of categories and tags for the blog
insert into public.categories (name, slug, description)
values
  ('Intelligence Systems', 'intelligence-systems', 'AI platforms and decision systems'),
  ('Geospatial & Earth Observation', 'geospatial-earth-observation', 'Remote sensing and GIS intelligence')
on conflict (slug) do nothing;

insert into public.tags (name, slug, description)
values
  ('AI', 'ai', 'Artificial Intelligence'),
  ('Automation', 'automation', 'Workflow & RPA'),
  ('Geospatial', 'geospatial', 'Remote sensing & GIS'),
  ('Forecasting', 'forecasting', 'Predictive modeling & EWS')
on conflict (slug) do nothing;

-- Sample blog post
insert into public.posts (title, slug, excerpt, content, published, published_at)
values
  ('Introducing ICTHubs: Intelligence. Insight. Action.', 'welcome-to-icthubs', 'We build intelligence and execution systems that help people and organizations make better decisions and take effective action at scale.', 'We build intelligence and execution systems that help people and organizations make better decisions and take effective action at scale. ICTHubs develops AI-powered platforms, digital infrastructure, and intelligent execution systems that transform data into decisions—and decisions into results.', true, now())
on conflict (slug) do nothing;
